name: 🤖 Attendance Automation Bot

on:
  schedule:
    # Run at 8:59 AM IST (clock-in) and 5:59 PM IST (clock-out)
    - cron: '00 2 * * 1-5'  # 8:59 AM IST (clock-in)
    - cron: '29 12 * * 1-5' # 5:59 PM IST (clock-out)
  workflow_dispatch: # Manual trigger for testing

jobs:
  run-bot:
    runs-on: self-hosted

    env:
      FIX: ${{ secrets.FIX }}
      PASSWORD: ${{ secrets.PASSWORD }}
      LOGIN_URL: ${{ secrets.LOGIN_URL }}
      # MONGO_URI: ${{ secrets.MONGO_URI }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: 📦 Install dependencies
      run: npm install

    - name: 🔧 Install Puppeteer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxkbcommon-x11-0 libnss3 libatk-bridge2.0-0 libgtk-3-0

    - name: ▶️ Run CLOCK-IN automation
      if: startsWith(github.event.schedule, '29 2')
      run: node patch.js clockin

    - name: ▶️ Run CLOCK-OUT automation
      if: startsWith(github.event.schedule, '29 12')
      run: node patch.js clockout
